### ISSUE TITLE
nxService: currently not working; stack dump & error are output when trying to use

### ISSUE THREAD

**Issue by eehret** [Azure/nxtools#25]
#### Details of the scenario you tried and the problem that is occurring
First, I realize that nxService isn't mentioned on the readme page as one of the nx resources I should expect to be working, so I suspect this is a work in progress.  Just mentioning in case the issue is not already known.
Basically if I try to use nxService, I get errors while trying to:

`Get-GuestConfigurationPackageComplianceStatus -Path ./MyConfig.zip`

#### Verbose logs showing the problem
Write-Error: Job b0c2b369-50a4-4b3e-880e-f6d58e61bf06 : MIResult: 1 Error Message: unknown propertyName:Load Message ID: OMI:MI_Result:1 Error Category: 0 Error Code: 1 Error Type:
Write-Error: Job b0c2b369-50a4-4b3e-880e-f6d58e61bf06 : MIResult: 1 Error Message: internal exception:System.Exception: unknown propertyName:Load    at
Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.CreateDscClassList(Hashtable getMethodOutput, String className, Boolean isEmbeddedClass, List`1 dscClasses, List`1 psClasses)
at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.GetInternal(String jsonRegistrationInstance, String jsonConfigInstance, String psModulePath, String& jsonGetOutput, String&
errorMessage)    at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, String jsonRegistrationInstance, String jsonConfigInstance, String
psModulePath, IntPtr& jsonGetOutput, IntPtr& errorMessage) Message ID: OMI:MI_Result:1 Error Category: 0 Error Code: 1 Error Type:
Write-Error: Job b0c2b369-50a4-4b3e-880e-f6d58e61bf06 : This event indicates that failure happens when LCM is processing the configuration. Error Id is 1. Error Detail is The SendConfigurationApply function did not
succeed.. Resource Id is [nxService]auditd_Running and Source Info is /home/azops.eric.ehret/azam/RHEL_auditd_configuration.ps1::111::5::nxService. Error Message is internal exception:System.Exception:
unknown propertyName:Load    at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.CreateDscClassList(Hashtable getMethodOutput, String className, Boolean isEmbeddedClass, List`1
dscClasses, List`1 psClasses)    at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.GetInternal(String jsonRegistrationInstance, String jsonConfigInstance, String psModulePath,
String& jsonGetOutput, String& errorMessage)    at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, String jsonRegistrationInstance, String json
Write-Error: Job b0c2b369-50a4-4b3e-880e-f6d58e61bf06 : MIResult: 1 Error Message: internal exception:System.Exception: unknown propertyName:Load    at
Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.CreateDscClassList(Hashtable getMethodOutput, String className, Boolean isEmbeddedClass, List`1 dscClasses, List`1 psClasses)
at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.GetInternal(String jsonRegistrationInstance, String jsonConfigInstance, String psModulePath, String& jsonGetOutput, String&
errorMessage)    at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, String jsonRegistrationInstance, String jsonConfigInstance, String
psModulePath, IntPtr& jsonGetOutput, IntPtr& errorMessage) Message ID: OMI:MI_Result:1 Error Category: 0 Error Code: 1 Error Type:

                                                                                                                           
This was preceeded by a stack trace like this:
                                                                                                    
Error: Failed to Run Consistency for 'RHEL-auditd-configuration-1_0_0' Error : unknown propertyName:Load
internal exception:System.Exception: unknown propertyName:Load
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.CreateDscClassList(Hashtable getMethodOutput, String className, Boolean isEmbeddedClass, List`1 dscClasses, List`1 psClasses)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.GetInternal(String jsonRegistrationInstance, String jsonConfigInstance, String psModulePath, String& jsonGetOutput, String& errorMessage)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, String jsonRegistrationInstance, String jsonConfigInstance, String psModulePath, IntPtr& jsonGetOutput, IntPtr& errorMessage)
internal exception:System.Exception: unknown propertyName:Load
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.CreateDscClassList(Hashtable getMethodOutput, String className, Boolean isEmbeddedClass, List`1 dscClasses, List`1 psClasses)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPsPluginWkrInternal.GetInternal(String jsonRegistrationInstance, String jsonConfigInstance, String psModulePath, String& jsonGetOutput, String& errorMessage)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, String jsonRegistrationInstance, String jsonConfigInstance, String psModulePath, IntPtr& jsonGetOutput, IntPtr& errorMessage)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
    # Ensure auditd service is enabled and running -- 4.1.1.2
    nxService auditd_Running {
      Name = "auditd"
      Enabled = $true
      State = "Running"
    }
```

#### The operating system the target node is running
This happened to be on Ubuntu 18.  Haven't tried reproducing with any other operating systems yet.

#### Version and build of PowerShell the target node is running
7.3.6

#### Version of the DSC module that was used
1.1.0

**Comment by eehret** [comment]
Also:  the property that it complains about can be different for each invocation of Get-GuestConfigurationPackageComplianceStatus (e.g. one time it will complain about 'Load' , next time it will complain about 'Reason', etc...)

**Comment by eehret** [comment]
@gurrajatwal Thanks so much for fixing this.   I am in urgent need of the new package containing this fix.   Do you know approximately how quickly we can expect the package in powershell gallery to be updated?
